CREATE USER C##1630289 IDENTIFIED BY "1630289" 
    DEFAULT TABLESPACE USERS TEMPORARY
    TABLESPACE TEMP;
    
--ALTER USER C##1730204 QUOTA UNLIMITED ON USERS;

GRANT C##ALUMNO_ORCL TO C##1630289;


SELECT 
         UPPER(FIRST_NAME) NOMBRE
        ,UPPER(LAST_NAME) APELLIDOS
        ,CONCAT(LOWER(EMAIL), '@empresa.com.mx') EMAIL
        ,LPAD(DEPARTMENT_ID, 4, '0') "COD_DEPARTMENTO"
    FROM C##ALUMNO.EMPLOYEES 
    WHERE DEPARTMENT_ID = 50;

SELECT RPAD('LUIS ROBERTO', 20, '-') FROM DUAL;

SELECT *
    FROM C##ALUMNO.EMPLOYEES
    WHERE LOWER(LAST_NAME) = 'vargas';
    
SELECT 
         FIRST_NAME, LAST_NAME
        ,LOWER(SUBSTR(FIRST_NAME, 1, 1) || '_' || LAST_NAME) || '@empresa.com'
    FROM
        C##ALUMNO.EMPLOYEES;
        
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') FROM DUAL;

    
    
    
