
-- Oracle 
SELECT E.LAST_NAME, E.FIRST_NAME, D.DEPARTMENT_NAME
    FROM EMPLOYEES E, DEPARTMENTS D
    WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
    ORDER BY E.LAST_NAME, E.FIRST_NAME;
    
-- ANSI/ISO SQL 99
SELECT E.LAST_NAME, E.FIRST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
    FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    ORDER BY E.LAST_NAME, E.FIRST_NAME;

-- Oracle
SELECT E.LAST_NAME, E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
    FROM EMPLOYEES E, DEPARTMENTS D
    WHERE E.DEPARTMENT_ID(+) = D.DEPARTMENT_ID
    ORDER BY D.DEPARTMENT_NAME, E.LAST_NAME, E.FIRST_NAME;
    
SELECT E.LAST_NAME, E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
    FROM EMPLOYEES E, DEPARTMENTS D
    WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID(+)
    ORDER BY D.DEPARTMENT_NAME, E.LAST_NAME, E.FIRST_NAME;

-- ANSI/ISO SQL 99
SELECT E.LAST_NAME, E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
    FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    ORDER BY D.DEPARTMENT_NAME, E.LAST_NAME, E.FIRST_NAME;    
    