
-- Union interna con natural JOIN.
SELECT LAST_NAME, FIRST_NAME, DEPARTMENT_NAME
    FROM EMPLOYEES NATURAL JOIN DEPARTMENTS
    ORDER BY LAST_NAME, FIRST_NAME;
    
SELECT LAST_NAME, FIRST_NAME, DEPARTMENT_NAME
    FROM EMPLOYEES E JOIN DEPARTMENTS D USING (DEPARTMENT_ID)
    ORDER BY LAST_NAME, FIRST_NAME;  
    
SELECT LAST_NAME, FIRST_NAME, DEPARTMENT_NAME
    FROM EMPLOYEES E JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    ORDER BY LAST_NAME, FIRST_NAME;  
    
SELECT 
         LAST_NAME
        ,FIRST_NAME
        ,NVL(DEPARTMENT_NAME, '[NO DEPARTMENT]') DEPT_NAME
    FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    ORDER BY LAST_NAME, FIRST_NAME;    
    
SELECT
         DEPARTMENT_NAME
        ,NVL(LAST_NAME, '[NO MANAGER]') "MANAGER"
    FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D
        ON D.MANAGER_ID = E.EMPLOYEE_ID
    ORDER BY DEPARTMENT_NAME;    
    
SELECT
         DEPARTMENT_NAME
        ,NVL(LAST_NAME, '[NO MANAGER]') "MANAGER"
    FROM DEPARTMENTS D LEFT OUTER JOIN EMPLOYEES E
        ON D.MANAGER_ID = E.EMPLOYEE_ID
    ORDER BY DEPARTMENT_NAME;    

-- Los depts que no tengan manager, unirlos con el employee 100.
SELECT
         DEPARTMENT_NAME
        ,D.MANAGER_ID
        ,LAST_NAME "MANAGER_NAME"
        ,EMAIL MANAGER_EMAIL
    FROM DEPARTMENTS D LEFT OUTER JOIN EMPLOYEES E
        ON NVL(D.MANAGER_ID, 100) = E.EMPLOYEE_ID
    ORDER BY DEPARTMENT_NAME;   
    

    
