SELECT 
         E.LAST_NAME || ' ' || E.FIRST_NAME EMPLEADO
        ,M.LAST_NAME || ' ' || M.FIRST_NAME JEFE
    FROM EMPLOYEES E JOIN EMPLOYEES M
        ON E.MANAGER_ID = M.EMPLOYEE_ID
    ORDER BY E.LAST_NAME, E.FIRST_NAME    ;
        
SELECT 
         E.LAST_NAME || ' ' || E.FIRST_NAME EMPLEADO
        ,M.LAST_NAME || ' ' || M.FIRST_NAME JEFE
    FROM EMPLOYEES E LEFT OUTER JOIN EMPLOYEES M
        ON E.MANAGER_ID = M.EMPLOYEE_ID
    ORDER BY E.LAST_NAME, E.FIRST_NAME    ;

SELECT 
         E.LAST_NAME || ' ' || E.FIRST_NAME EMPLEADO
        ,M.LAST_NAME || ' ' || M.FIRST_NAME JEFE
    FROM EMPLOYEES E LEFT OUTER JOIN EMPLOYEES M
        ON NVL(E.MANAGER_ID, 100) = M.EMPLOYEE_ID
    ORDER BY E.LAST_NAME, E.FIRST_NAME    ;

SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL;

SELECT LEVEL, LAST_NAME EMPLEADO, PRIOR LAST_NAME JEFE
    FROM EMPLOYEES
    START WITH EMPLOYEE_ID = 100
    CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
    ORDER BY LEVEL;
    
SELECT LPAD(LAST_NAME, LENGTH(LAST_NAME) + (LEVEL * 2) - 2, '-') ORG_CHAR
    FROM EMPLOYEES
    START WITH EMPLOYEE_ID = 100
    CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;
    
SELECT LPAD(LAST_NAME, LENGTH(LAST_NAME) + (LEVEL * 2) - 2, '-') ORG_CHAR
    FROM EMPLOYEES
    START WITH LAST_NAME = 'Kochhar'
    CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;
