
SELECT COUNT(*) COUNT_EMPLOYEES FROM EMPLOYEES;

SELECT COUNT(COMMISSION_PCT) CANT_EMPLOYEES_COMM FROM EMPLOYEES;
SELECT COUNT(*) CANT_EMPLOYEES_COMM
    FROM EMPLOYEES
    WHERE COMMISSION_PCT IS NOT NULL;
    
SELECT  COUNT(*) CANT_EMPL
    FROM EMPLOYEES
    WHERE HIRE_DATE < TO_DATE('1995-01-01', 'YYYY-MM-DD');

SELECT DISTINCT JOB_ID
    FROM EMPLOYEES;

SELECT DISTINCT JOB_ID, DEPARTMENT_ID
    FROM EMPLOYEES
    ORDER BY JOB_ID;
    
SELECT COUNT(DISTINCT JOB_ID) FROM EMPLOYEES;

SELECT AVG(COMMISSION_PCT) FROM EMPLOYEES;
SELECT AVG(NVL(COMMISSION_PCT, 0)) FROM EMPLOYEES;
SELECT AVG(NVL(COMMISSION_PCT, 0.01)) FROM EMPLOYEES;

SELECT DEPARTMENT_ID, AVG(SALARY) AVG_SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID IS NOT NULL
    GROUP BY DEPARTMENT_ID
    HAVING AVG(SALARY) > 9000
    ORDER BY AVG(SALARY) DESC;
    
SELECT DEPARTMENT_ID, COUNT(*) CANT_EMPL
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
    HAVING COUNT(*) > 1
    ORDER BY COUNT(*);
    


