
-- JOIN NATURAL
SELECT 
         LAST_NAME
        ,FIRST_NAME
        ,JOB_ID
        ,JOB_TITLE
        ,SALARY
        ,MIN_SALARY
        ,MAX_SALARY
    FROM EMPLOYEES NATURAL JOIN JOBS
    ORDER BY LAST_NAME, FIRST_NAME;
    
-- JOIN NATURAL
SELECT
         DEPARTMENT_NAME
        ,CITY
        ,STATE_PROVINCE
        ,LOCATION_ID
    FROM DEPARTMENTS NATURAL JOIN LOCATIONS
    WHERE STATE_PROVINCE IS NOT NULL
    ORDER BY DEPARTMENT_NAME;    
    
-- JOIN NATURAL
SELECT
         DEPARTMENT_NAME
        ,CITY
        ,STATE_PROVINCE
    FROM DEPARTMENTS NATURAL JOIN LOCATIONS
    WHERE STATE_PROVINCE IS NOT NULL AND LOCATION_ID > 1700
    ORDER BY DEPARTMENT_NAME;

-- CROSS JOIN -> UNION CRUZADA PARA COMBINACIÓN
SELECT
         LAST_NAME
        ,FIRST_NAME
        ,DEPARTMENT_NAME
    FROM EMPLOYEES CROSS JOIN DEPARTMENTS
    ORDER BY DEPARTMENT_NAME, LAST_NAME, FIRST_NAME;    

-- JOIN CON "USING"
SELECT
        LAST_NAME
        ,FIRST_NAME
        ,DEPARTMENT_NAME
    FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
    --WHERE LAST_NAME = 'Fay'
    ORDER BY LAST_NAME, FIRST_NAME;

-- JOIN CON "ON"
SELECT
         LAST_NAME
        ,FIRST_NAME
        ,DEPARTMENT_NAME
    FROM 
        EMPLOYEES E 
            JOIN 
        DEPARTMENTS D 
            ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    --WHERE LAST_NAME = 'Fay'
    ORDER BY LAST_NAME, FIRST_NAME;

-- JOIN CON "ON"
SELECT
        LAST_NAME
        ,FIRST_NAME
        ,JOB_TITLE
    FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID
    ORDER BY LAST_NAME, FIRST_NAME ;
    
/*
 * 1. Consultar los registro de la tabla COUNTRIES
 *    uniendo con la tabla REGIONS.
 *    Proyección: COUNTRY_NAME, REGION_NAME.
 *    Nota: Usar Natural Join, Join con Using
 *    y Join con ON.
 */
SELECT COUNTRY_NAME, REGION_NAME
    FROM COUNTRIES NATURAL JOIN REGIONS
    ORDER BY REGION_NAME, COUNTRY_NAME;
    
SELECT COUNTRY_NAME, REGION_NAME
    FROM COUNTRIES JOIN REGIONS USING (REGION_ID)
    ORDER BY REGION_NAME, COUNTRY_NAME;
 
SELECT COUNTRY_NAME, REGION_NAME
    FROM COUNTRIES C JOIN REGIONS R ON R.REGION_ID = C.REGION_ID
    ORDER BY REGION_NAME, COUNTRY_NAME;
 
/*
 * 2. Consultar los registros de la unión de la tabla
 *    LOCATIONS con COUNTRIES.
 *    Proyección: STREET_ADDRESS, POSTAL_CODE, CITY,
 *    STATE_PROVINCE, COUNTRY_NAME.
 *    Nota: Usar Natural Join, Join con Using
 *    y Join con ON.
 */
SELECT STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_NAME
    FROM LOCATIONS NATURAL JOIN COUNTRIES
    ORDER BY COUNTRY_NAME, STATE_PROVINCE, CITY;
    
SELECT STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_NAME
    FROM LOCATIONS JOIN COUNTRIES USING (COUNTRY_ID)
    ORDER BY COUNTRY_NAME, STATE_PROVINCE, CITY;
        
SELECT STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_NAME
    FROM LOCATIONS L JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
    ORDER BY COUNTRY_NAME, STATE_PROVINCE, CITY;
 
/*
 * 3. Consultar los DEPARTMENTS y su MANAGER (EMPLOYEES table),
 *    Proyección: DEPARTMENT_NAME, FULL_NAME del manager (concatenar).
 *    Selección: Solo los deparments que tengan manager.
 */
SELECT DEPARTMENT_NAME, FIRST_NAME || ' ' || LAST_NAME AS "MANAGER"
    FROM DEPARTMENTS D JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID;
    
SELECT DEPARTMENT_NAME, FIRST_NAME || ' ' || LAST_NAME AS "MANAGER"
    FROM DEPARTMENTS D LEFT OUTER JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
    ORDER BY DEPARTMENT_NAME;

SELECT 
         DEPARTMENT_NAME
        ,NVL2(LAST_NAME, FIRST_NAME || ' ' || LAST_NAME, '[SIN ADMIN]') AS "MANAGER"
    FROM DEPARTMENTS D LEFT OUTER JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
    ORDER BY DEPARTMENT_NAME;

SELECT * FROM DEPARTMENTS; 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 