
SELECT MIN(SALARY) MIN_SALARY FROM EMPLOYEES;

SELECT MAX(SALARY) MAX_SALARY FROM EMPLOYEES;

SELECT 
         MAX(SALARY) MAX_SALARY
        ,MIN(SALARY) MIN_SALARY
        ,AVG(SALARY) AVG_SALARY
    FROM EMPLOYEES;
    
SELECT 
         MAX(SALARY) MAX_SALARY
        ,MIN(SALARY) MIN_SALARY
        ,AVG(SALARY) AVG_SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 100;
    
SELECT MIN(HIRE_DATE), MAX(HIRE_DATE) FROM EMPLOYEES WHERE DEPARTMENT_ID = 100;

SELECT
         DEPARTMENT_ID
        ,MIN(SALARY) MIN_SALARY
        ,MAX(SALARY) MAX_SALARY
        ,AVG(SALARY) AVG_SALARY
        ,SUM(SALARY) SUM_SALARY
    FROM EMPLOYEES
    --WHERE DEPARTMENT_ID >= 100
    GROUP BY DEPARTMENT_ID
    ORDER BY DEPARTMENT_ID;
    
