SELECT COUNTRY_NAME, REGION_NAME
      FROM COUNTRIES NATURAL JOIN REGIONS
      ORDER BY REGION_NAME,COUNTRY_NAME;
      
      
      SELECT COUNTRY_NAME,REGION_NAME
      FROM COUNTRIES JOIN REGIONS USING (REGION_ID)
      ORDER BY REGION_NAME, COUNTRY_NAME;
      
      SELECT COUNTRY_NAME,REGION_NAME
      FROM COUNTRIES C JOIN REGIONS R ON R.REGION_ID = C.REGION_ID
      ORDER BY REGION_NAME,COUNTRY_NAME;
      
      
      /**********************************************/
      SELECT STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_NAME
      FROM LOCATIONS NATURAL JOIN COUNTRIES
      ORDER BY COUNTRY_NAME, STATE_PROVINCE, CITY;
      
         SELECT STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_NAME
      FROM LOCATIONS JOIN COUNTRIES USING (COUNTRY_ID)
      ORDER BY COUNTRY_NAME, STATE_PROVINCE, CITY;
      
         SELECT STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_NAME
      FROM LOCATIONS L JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
      ORDER BY COUNTRY_NAME, STATE_PROVINCE, CITY;
      
      /*******************************************/
      
      SELECT DEPARTMENT_NAME, FIRST_NAME || ' ' || LAST_NAME AS "MANAGER"
      FROM DEPARTMENTS D JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID;
      
      SELECT DEPARTMENT_NAME, FIRST_NAME || ' ' || LAST_NAME AS "MANAGER"
      FROM DEPARTMENTS D LEFT OUTER JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID;
      ORDER BY DEPARTMENT_NAME;
      
          SELECT DEPARTMENT_NAME
          ,NVL2(LAST_NAME, FIRST_NAME || ' ' || LAST_NAME,'[SIN ADMIN]') AS "MANAGER"
      FROM DEPARTMENTS D LEFT OUTER JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID;
      ORDER BY DEPARTMENT_NAME;
      
      SELECT * FROM DEPARTMENTS;