/*
 *  == diseño de base de datos ==
 *  ==  R5ecuperacion unidad 3 ==
 */

/*
1. obtenga LOS Department QUE  TENGAN LA MAYOR CANTIDAD DE JOB_TITLE 
y el Department que tenga la MENOR cantidad  de empleados.
columnas:DEPARMENT_NAME,STREET_ADDRESS. COUNTRY_NAME, REGION_NAME Y JOB TITLE
AS MANAGER_JOB_TITLE), CANT_JOB_TITLE, CANT_EMPLOYEES.

*/
SELECT * FROM (SELECT 
                 DEPARTMENT_NAME
                ,STREET_ADDRESS
                ,COUNTRY_NAME
                ,REGION_NAME
                ,(SELECT COUNT(DISTINCT JOB_ID) FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) CANT_JOB_TITLE,
                 (SELECT COUNT(*) FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) CANT_EMPLOYEES 
            FROM
                DEPARTMENTS D
                INNER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID 
                INNER JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
                INNER JOIN REGIONS R ON C.REGION_ID = R.REGION_ID) SUB1
WHERE 
CANT_JOB_TITLE =(SELECT MAX(CANT_JOB_TITLE) FROM (SELECT  DEPARTMENT_NAME ,(SELECT COUNT(DISTINCT JOB_ID) 
FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) CANT_JOB_TITLE FROM DEPARTMENTS D) SUB2) 
OR
CANT_EMPLOYEES =(SELECT MIN(CANT_EMPLOYEES) FROM (SELECT DEPARTMENT_ID, COUNT(*) CANT_EMPLOYEES FROM EMPLOYEES GROUP BY DEPARTMENT_ID))
ORDER BY CANT_JOB_TITLE;





