SELECT LAST_NAME, FIRST_NAME,HIRE_DATE
  FROM EMPLOYEES
  WHERE EXTRACT(YEAR FROM HIRE_DATE) < ANY
           (SELECT EXTRACT(YEAR FROM HIRE_DATE)
                  FROM EMPLOYEES
                  WHERE DEPARTMENT_ID = 90);
                  
--Cual es el empleado que gana mas y cual es el que 
--gana menos. EN UNA SOLA SENTENCIA SELECT!
SELECT LAST_NAME, FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE 
SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES) OR
SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

/////////////////////////////////////////////////
SELECT LAST_NAME, FIRST_NAME, SALARY, D.DEPARTMENT_NAME
 FROM EMPLOYEES E
   JOIN
   DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN 
    DEPARTMENTS D 
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN 
    JOBS J
    ON E.JOB_ID = J.JOB_ID
    WHERE
    SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES) OR
    SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

--Cuales son los deparments que no tienen empleados con el 
--job_title de 'Stock Clerk' ni 'President'.
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID NOT IN
(SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES 
WHERE EMPLOYEE_ID IN (
SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE JOB_ID IN
(SELECT JOB_ID 
FROM JOBS WHERE 
JOB_TITLE IN ('President', 'Stock Clerk'))));

////////////////////////////////////////////////////////////////////
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID NOT IN 
(SELECT DISTINCT DEPARTMENT_ID
  FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID
  WHERE J.JOB_TITLE IN ('President', 'Stok Clerk'));
  
  SELECT DEPARTMENT_ID, DEPARTMENT_NAME
     FROM DEPARTMENTS D
     WHERE NOT EXISTS
     (SELECT *
        FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID
        WHERE
        J.JOB_TITLE IN ('President', 'Stock Clerk') AND
        D.DEPARTMENT_ID = E.DEPARTMENT_ID);
        
--De quien es el salario mayor que el salrio medio de su departamento.
SELECT E1.FIRST_NAME, E1.LAST_NAME, E1.SALARY 
    FROM EMPLOYEES E1
    WHERE E1.SALARY > 
    (SELECT AVG(SALARY) 
    FROM EMPLOYEES E2
    WHERE E1.DEPARTMENT_ID = E2.DEPARTMENT_ID);