CREATE TABLE EMPLEADOS(
  ID_EMPLEADO NUMBER (6) NOT NULL PRIMARY KEY,
  APELLIDO_PATERNO VARCHAR2(64) NOT NULL,
  APELLIDO_MATERNO VARCHAR2(64) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  CURP CHAR(28) NOT NULL,
  DEPARTAMENTO NUMBER (5) NOT NULL,
  EMAIL VARCHAR2 (128) NOT NULL
);

DROP TABLE ESTABLECIMIENTO;

CREATE TABLE ESTABLECIMIENTO(
  ID_ESTABLECIMIENTO NUMBER(16) NOT NULL PRIMARY KEY,
  MUNICIPIO VARCHAR2(64) NOT NULL,
  ESTADO VARCHAR2(64) NOT NULL,
  CIUDAD VARCHAR2(64) NOT NULL
);

CREATE TABLE USUARIOS(
  ID_USUARIOS NUMBER(16) NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR2(64) NOT NULL,
  APELLIDO_MATERNO VARCHAR2(64) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  DOMICILIO VARCHAR2 (64) NOT NULL,
  FECHA_REGISTRO DATE NOT NULL
);

DROP TABLE INVENTARIO;

CREATE TABLE INVENTARIO(
  ID_VEHICULOS NUMBER(5) NOT NULL PRIMARY KEY,
  MARCA VARCHAR2(64) NOT NULL,
  MODELO VARCHAR2(128) NOT NULL,
  ANO NUMBER(4) NOT NULL,
  COLOR VARCHAR2(64) NOT NULL,
  CANTIDAD_PASAJEROS VARCHAR2(128) NOT NULL,
  FECHA_ADQUISICION DATE NOT NULL
);

CREATE TABLE APARTADOS(
  ID_APARTADO NUMBER(6) NOT NULL PRIMARY KEY,
  FECHA_APARTADO DATE NOT NULL,
  NUM_SERIE VARCHAR2(6) NOT NULL,
  FECHA_ENTREGA DATE NOT NULL,
  ID_SUCURSAL NUMBER(6) NOT NULL
);

CREATE TABLE RETORNO_VEHICULO(
  ID_APARTADO NUMBER(5) NOT NULL PRIMARY KEY,
  FECHA_ENTREGA DATE NOT NULL,
  DIAS_RETRASO VARCHAR2(2) NOT NULL,
  HORAS_RETRASO NUMBER(2) NOT NULL
);