DROP TABLE EMPLEADOS;

CREATE TABLE EMPLEADOS (
  ID_EMPLEADO NUMBER (6) NOT NULL PRIMARY KEY,
  APELLIDO_PATERNO VARCHAR2(64) NOT NULL,
  APELLIDO_MATERNO VARCHAR2(64) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  CURP CHAR(28) NOT NULL,
  DEPARTAMENTO NUMBER (5) NOT NULL,
  EMAIL VARCHAR2 (128) NOT NULL,
  TELEFONO NUMBER(13) NOT NULL,
  FECHA_CONTRATACION DATE NOT NULL,
  FECHA_FIN_TRABAJO DATE NOT NULL,
  SEXO VARCHAR2(2) NOT NULL
);

DROP TABLE ESTABLECIMIENTO;

CREATE TABLE ESTABLECIMIENTO (
  ID_ESTABLECIMIENTO NUMBER(16) NOT NULL PRIMARY KEY,
  MUNICIPIO VARCHAR2(64) NOT NULL,
  ESTADO VARCHAR2(64) NOT NULL,
  CIUDAD VARCHAR2(64) NOT NULL,
  NUMERO_CLIENTE NUMBER(20) NOT NULL
);

DROP TABLE USUARIOS;

CREATE TABLE USUARIOS (
  ID_USUARIOS NUMBER(16) NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR2(64) NOT NULL,
  APELLIDO_PATERNO VARCHAR2(64) NOT NULL,
  APELLIDO_MATERNO VARCHAR2(64) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  DOMICILIO VARCHAR2 (64) NOT NULL,
  FECHA_REGISTRO DATE NOT NULL,
  SEXO VARCHAR2(2) NOT NULL
);

DROP TABLE INVENTARIO;

CREATE TABLE INVENTARIO (
  ID_VEHICULOS NUMBER(5) NOT NULL PRIMARY KEY,
  MARCA VARCHAR2(64) NOT NULL,
  MODELO VARCHAR2(128) NOT NULL,
  ANO NUMBER (4) NOT NULL,
  COLOR VARCHAR2 (64) NOT NULL,
  CANTIDAD_PASAJEROS VARCHAR2 (128) NOT NULL,
  FECHA_ADQUISICION DATE NOT NULL
);

CREATE TABLE CAMBIOS (
  ID NUMBER(5) NOT NULL PRIMARY KEY,
  ID_EMPLEADO NUMBER(5) NOT NULL,
  ID_SUCURSAL NUMBER(10) NOT NULL,
  RESTO VARCHAR2(64) NOT NULL
);

DROP TABLE APARTADOS;

CREATE TABLE APARTADOS (
  ID_APARTADO NUMBER(6) NOT NULL PRIMARY KEY,
  FECHA_APARTADO DATE NOT NULL,
  ID_CLIENTE NUMBER(5) NOT NULL,
  ID_VEHICULO NUMBER(6) NOT NULL,
  NUM_SERIE VARCHAR2(6) NOT NULL,
  STATUS_APARTADO VARCHAR2(64) NOT NULL,
  FECHA_ENTREGA_CARRO DATE NOT NULL,
  ID_SUCURSAL NUMBER(6) NOT NULL
);

DROP TABLE RETORNO_VEHICULO;

CREATE TABLE RETORNO_VEHICULO (
  ID_APARTADO NUMBER(5) NOT NULL PRIMARY KEY,
  FECHA_ENTREGA DATE NOT NULL,
  DIAS_RETRASO VARCHAR2(2) NOT NULL,
  HORAS_RETRASO NUMBER(2) NOT NULL,
  KM_ENTREGA NUMBER(24) NOT NULL
);